name: Test
 
on:
  push:
    branches: [ main ] 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js 20.x (LTS)
      uses: actions/setup-node@v2
      with:
        node-version: 20.x
    - name: Install and test
      run: |
        yarn
        yarn test
